### ISSUE TITLE
远程库用不了

### ISSUE THREAD

**Issue by Zane-cqupt** [Jude95/RollViewPager#1]
远程库导入不了我的项目里面。。。

**Comment by Jude95** [comment]
项目gradle的仓库设置里没有添加jcenter？或者是网络问题。翻墙试试。

**Comment by Zane-cqupt** [comment]
可是其他的远程库比如ButterKinef这些我都可以直接添加

**Comment by Zane-cqupt** [comment]
请问你这个库有没有jar包？

**Comment by Jude95** [comment]
那应该就是你没添加jcenter吧。我这边都是没问题的。这个包含资源文件是不可能做成jar包的。有arr包。你远程依赖就是在下arr包。

**Comment by Zane-cqupt** [comment]
谢谢了，我再试试！

**Comment by Zane-cqupt** [comment]
as添加jccenter是在build.gradle里面添加这段代码吗？我好像加了之后还是不能用你的库
allprojects {
    repositories {
        mavenCentral()
    }
}

**Comment by Zane-cqupt** [comment]
allprojects {
    repositories {
        jcenter()
    }
}
刚刚复制错了

**Comment by Jude95** [comment]
= =。QQ：973829691
