### ISSUE TITLE
使用的loopadapter，在一张图片的情况下，不会自动轮播，但是还是可以滑动出现视图错位

### ISSUE THREAD

**Issue by tmac010sjh** [Jude95/RollViewPager#10]
建议在只有一张图片的情况下，禁止viewpager的滑动

**Comment by Jude95** [comment]
看看1.2.8版本

**Comment by tmac010sjh** [comment]
问题解决了，但是在动态改变图片张数至一张的情况下，还是需要手动setHintView(null),个人觉得在一张图片的情况下不需要指示点，最后，荆轲刺秦王！

**Comment by xuejinwei** [comment]
@tmac010sjh  请问如何解决的？？
