### ISSUE TITLE
滑动不好使

### ISSUE THREAD

**Issue by TroyRay** [Jude95/RollViewPager#11]
滑动不好使，在右侧向左滑的时候很难滑动到下一页

**Comment by Jude95** [comment]
。。为什么。滑动部分就是普通的viewpager又没有动什么。

**Comment by hanzhifengyun** [comment]
加载网络数据，设置adapter程序会ANR
adapter 刷新时 指示器并没有重置
应该添加 start 和 stop 轮播接口

**Comment by Jude95** [comment]
什么导致的ANR，这个库并没有什么能导致无响应的机制..他只是个adapter啊。
adapter我测试完美支持notifyDataSetChange，getCount返回数据减少后，指示器的item也是正常减少。
第一次遇到这种需求...已添加，待上面的问题解决了发布。

**Comment by goodsfile** [comment]
```
public static void showBanner(final Context context, RollPagerView mRollPagerView, final String[] GoodsImg){
        mRollPagerView.setAnimationDurtion(500);
        mRollPagerView.setAdapter(new LoopPagerAdapter(mRollPagerView) {
            @Override
            public View getView(ViewGroup container, int position) {
                ImageView view = new ImageView(context);
                Glide.with(context).load(Constants.URL_Goods_IMG+"/"+GoodsImg[position]).into(view);
                view.setScaleType(ImageView.ScaleType.CENTER_CROP);
                view.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
                return view;
            }

            @Override
            protected int getRealCount() {
                return GoodsImg.length;
            }
        });
        mRollPagerView.setHintView(new ColorPointHintView(context, Color.WHITE, Color.GRAY));
```

我请求网络，加载图片 直接anr  不知道怎么回事，作者 有没有做过这个？

**Comment by Jude95** [comment]
这样的需求做过无数遍。
你可以查一查是哪一行代码ANR？
这段代码看不出什么问题。
另外把VIew设为static不是好习惯。

**Comment by goodsfile** [comment]
哪里把view设置static？

**Comment by Jude95** [comment]
。。没事，还以为`mRollPagerView `是个成员变量。结果是参数。找到哪里ANR了吗？

**Comment by goodsfile** [comment]
我就是在加载图片 的时间过长，当再次进入页面 还是 加载 图片，不能从缓存中读取，这就是造成anr，你有什么好的方法

**Comment by Jude95** [comment]
这与RollViewPager没关系吧..
= =没明白你的逻辑，异步加载图片时间过长与不能从缓存中读取有什么关系吗。为什么不能从缓存读取。为什么就造成ANR了。

**Comment by Jude95** [comment]
ANR可能是老版本对LooperPagerAdapter进行notifydatasetchange引发。
ViewPager一个View还真能ANR...
现在还有问题吗

**Comment by msantsta** [comment]
为什么我的刚刚开始第一次往左滑动滑不了呢？

 private  class FragmentViewpagerAdapter extends LoopPagerAdapter {

        public FragmentViewpagerAdapter(RollPagerView viewPager) {
            super(viewPager);
        }

        @Override
        public View getView(ViewGroup container, int position) {
            ImageView imageview = new ImageView(container.getContext());
            Picasso.with(getActivity()).load(list1.get(position).getItemImage()).into(imageview);
            imageview.setScaleType(ImageView.ScaleType.CENTER_CROP);
            imageview.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT ));
            return imageview;
        }

        @Override
        protected int getRealCount() {

            return list1.size() ;
        }
    }

**Comment by Jude95** [comment]
@msantsta 请新建issue
