### ISSUE TITLE
添加文字

### ISSUE THREAD

**Issue by xxwywzy** [Jude95/RollViewPager#16]
请问可以为轮播页添加文字随图片一起滚动播放吗

**Comment by Jude95** [comment]
那只是个ViewPager。。你给每一页里加一个TextView不就好了。

**Comment by xxwywzy** [comment]
那个我在getview方法中加入了textview，那应该如何与imageview一起return呢，我是小白。。。

**Comment by Jude95** [comment]
和imageview一起add进一个Layout里面。
或者你写个xml去inflate再findviewbyid。

**Comment by xxwywzy** [comment]
搞定了！非常感谢！

**Comment by liubaozhongha** [comment]
textview 再轮播图外面，怎么根据轮播图滚动，而改变文字那？
