### ISSUE TITLE
网络图片部分加载不出来

### ISSUE THREAD

**Issue by TroyRay** [Jude95/RollViewPager#18]
使用LoopPagerAdapter的时候，会有部分网络图片加载不出来，不入有加载了5张网络图片，可能就会有三张网络图片加载不出来，然后重新刷新又会出来

**Comment by Jude95** [comment]
你这样描述我很难帮助你啊。
你能找一找具体原因吗？
是不是并发问题？
你的ImageView是在每一页View里面，讲道理不会有什么影响。。
