### ISSUE TITLE
外层viewpager  滑动事件冲突.  

### ISSUE THREAD

**Issue by scaPEGoatno** [Jude95/RollViewPager#2]

**Comment by Jude95** [comment]
呃，我这个是标准ViewPager，没有对触摸事件传递进行额外处理。
ViewPager会对手势进行判断，如果可滑动（比如在最后一页手指向右滑），就会拦截并处理手势。如果不可滑动（比如在最后一页手指向左滑），就不拦截事件，事件返回给上一级View。如果你在这个ViewPager外面再套一层的话，这时候它才能接受并处理手势。
如果你并不想这样。请自定义外层ViewPager先行处理事件，并编写合适的规则将事件拦截或传递给里层ViewPager。
