### ISSUE TITLE
循环播放时卡顿

### ISSUE THREAD

**Issue by HeXiaosa** [Jude95/RollViewPager#21]
轮播图循环时，要等很久才能加载出图片是什么原因呢，求解答
补充：是在请求网络之后再加载要等很久才能加载，尽管轮播图没有用到任何网络数据，setAdapter也执行完了，图片还是没有出来，用PagerView也有这种情况

**Comment by Jude95** [comment]
用ViewPager也是这样的问题那就是你的代码问题了。
问代码问题请贴代码。

**Comment by HeXiaosa** [comment]
/**
     * 获取轮播图图片
     */
    private void loadImageLoad() {
        HashMap<String, String> params = new HashMap<>();
        loadeDataGet(params, getImageLoadUrl, new Callback.CommonCallback<String>() {
            @Override
            public void onSuccess(String result) {
                Log.e(TAG, "onSuccess: " + result);
                try {
                    CheckResultUtil.checkResult(getContext(), result, new CheckImageLoad());
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void onError(Throwable ex, boolean isOnCallback) {
                ToastUtil.showShort(context, R.string.check_net);
            }

            @Override
            public void onCancelled(CancelledException cex) {
            }

            @Override
            public void onFinished() {
            }
        });
    }

    private class CheckImageLoad implements CheckHttpResultCallBack {

        @Override
        public void successCallBack(JSONObject result) {
            getImageLoad(result);
        }

        @Override
        public void failedCallBack(String errMsg) {
        }
    }

    private void getImageLoad(JSONObject result) {
        try {
            JSONArray retval = result.getJSONArray("retval");
            int length = retval.length();//轮播图个数

            final HashMap<Integer, String> urlMap = new HashMap<>();
            final HashMap<Integer, String> goodIdMap = new HashMap<>();
            final HashMap<Integer, String> gameIdMap = new HashMap<>();
            urlMap.clear();
            goodIdMap.clear();
            for (int i = 0; i < length; i++) {
                JSONObject jsonObject = retval.getJSONObject(i);
                urlMap.put(i, APIConfig.BOOT + jsonObject.getString("image_url"));
                goodIdMap.put(i, jsonObject.getString("gameitem_id"));
                gameIdMap.put(i, jsonObject.getString("game_id"));
            }
            handler.post(new Runnable() {
                @Override
                public void run() {
                    viewPager.setHintView(new IconHintView(context, R.mipmap.circle_focus, R.mipmap.circle_normal));
                    viewPager.setAdapter(new MyRollPagerAdapter(context, urlMap, goodIdMap, gameIdMap));
                }
            });
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }
抱歉现在才回，这个获取数据的方法是这个工程里面都是这样写的，为什么循环播放时会加载很久并引起ANR，但是最后会加载出来，现在不是循环播放的。多谢了！

**Comment by Jude95** [comment]
抱歉最近比较忙，问题解决了吗。我也不能从你这部分代码里看出问题。

**Comment by HeXiaosa** [comment]
没解决，我就先没让循环播放

**Comment by Jude95** [comment]
你是用的support包是v22的吗？
