### ISSUE TITLE
如果使用LoopPagerAdapter，会有一些小问题

### ISSUE THREAD

**Issue by XhosaS** [Jude95/RollViewPager#25]
如果使用LoopPagerAdapter，在配合上Picasso轮播网络图片时，如果网络图片稍大，会导致页面挂起，等待Picasso图片加载完毕后才会恢复，而使用staticPagerAdapter时没有这个问题。

**Comment by Biswangluo** [comment]
遇到了 同样问题 ANR了 用的imageloader

**Comment by Jude95** [comment]
为什么...
新的demo我也改为了网络图片。图片也很大。没问题。
我如何复现你们的问题？或者你们找找具体原因？

**Comment by chenyp1994** [comment]
@Jude95 我也遇到了ANR的问题。我的界面是顶部是一个轮播，下面还有个RecyclerView，Item也是图片加载。

**Comment by Jude95** [comment]
@chenyp1994 我如何复现你们的问题？我已经写了网络图片的demo。你们也写个试试？如果有问题将demo发我。我处理。

**Comment by chenyp1994** [comment]
@Jude95 你随便是两个接口就行了，http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1和http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/2。自己写个网络请求解析一下，JSON里面就有个图片URL，自己构建个List，试一下就可以发现了。我这边试了，确实如此。也在你的DEMO的基础上写的。

**Comment by chenyp1994** [comment]
@Jude95 你随便是两个接口就行了，
> http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1
> http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/2
自己写个网络请求解析一下，JSON里面就有个图片URL，自己构建个List，试一下就可以发现了。我这边试了，确实如此。也在你的DEMO的基础上写的。

**Comment by himon** [comment]
也遇到了，用的Glide，页面会卡住很长时间

**Comment by Jude95** [comment]
@chenyp1994 已经改为你的接口。依然没有问题。代码已push。

**Comment by chenyp1994** [comment]
@Jude95 可能我之前的版本比较久吧。现在没问题了，不过发现了一个问题。
你这里用反射好像有问题。也有可能是support包更新导致的。。
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err: java.lang.NoSuchFieldException: mCurItem
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at java.lang.Class.getField(Class.java:724)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at com.jude.rollviewpager.adapter.LoopPagerAdapter.initPosition(LoopPagerAdapter.java:55)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at com.jude.rollviewpager.adapter.LoopPagerAdapter.notifyDataSetChanged(LoopPagerAdapter.java:40)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at com.jude.rollviewpagerdome.MainActivity$TestLoopAdapter.setImgs(MainActivity.java:116)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at com.jude.rollviewpagerdome.MainActivity$3$1.run(MainActivity.java:75)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at android.os.Looper.loop(Looper.java:136)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5114)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
08-23 15:54:35.250 28408-28408/com.jude.rollviewpagerdome W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by chenyp1994** [comment]
@Jude95 我想我大概知道ANR的原因了。因为setCurrentItem()会导致一开始，ViewPager已经过多的滑动导致的。ViewPager的serCurrentItem()会滑动。

**Comment by chenyp1994** [comment]
在LoopPagerAdapter的initPostion方法里面改成这样就可以避免这个问题。
if (getCount() <= 1) return;
int half = 100 / 2;
int start = half - half % getRealCount();
mViewPager.getViewPager().setCurrentItem(start);

**Comment by Jude95** [comment]
@chenyp1994 说一下你NoSuchFieldException发生的support包版本

**Comment by tangjw** [comment]
Field field = ViewPager.class.getField("mCurItem"); ------> NoSuchFieldException
Field field = ViewPager.class.getDeclaredField("mCurItem");-----> ok

**Comment by tangjw** [comment]
rollPagerView.setAdapter(mBannerAdapter);
		mImgs = new int[]{R.drawable.img1, R.drawable.img2};
		mBannerAdapter.add(mImgs);
		
		new Handler().postDelayed(new Runnable() {
			@Override
			public void run() {
				mImgs = new int[]{R.drawable.img3, R.drawable.img4};
				mBannerAdapter.add(mImgs);
			}
		}, 2000L);

这段代码执行完毕图片错乱(显示的还是img1和img2), 本人菜鸟一枚,求大神解惑啊

**Comment by chenyp1994** [comment]
@Jude95      24.2.0

**Comment by Jude95** [comment]
@tangjw @chenyp1994 试试1.4.1   不好意思了。测试不严谨。

**Comment by chenyp1994** [comment]
还是会出现ANR，估计反射就解决不了这个问题。我是这样觉得，我改了再项目上还是不行。我还是把值改小点就好了。

**Comment by Jude95** [comment]
@chenyp1994 能帮忙找一下原因吗，或者给我一个ANR的场景，如何重现，demo没有问题。

**Comment by Jude95** [comment]
1.4.5 试试吧。= =我在尽力。

**Comment by tou-zhou** [comment]
同样出现使用LoopPagerAdapter界面挂起。 版本 1.4.5

**Comment by Jude95** [comment]
@tou-zhou 抱歉这么久没空维护，1.4.5如何ANR的，还能告诉我如何复现吗。

**Comment by tou-zhou** [comment]
@Jude95 我是从服务器获取图片地址，然后在activity 调用此开源库，然后，界面会白屏，卡住。直到加载完，才回恢复正常。加载adapter使用的loopPagerAdapter，使用其他的没问题

**Comment by zsyh** [comment]
我也出问题了，在issue#41，只要启动新线程并且在新线程中使用某种消息机制(比如runOnUiThread,broadcastReceiver等)传递到主线程进行setAdpater(new LoopPagerAdapter(rollPagerView));就会发生ANR

**Comment by Jude95** [comment]
新版本已解决。如有问题请新开issue
