### ISSUE TITLE
神,部分机型会出现OOM,然后图片显示黑色

### ISSUE THREAD

**Issue by dursss** [Jude95/RollViewPager#27]
在魅蓝上是好的
但是在三星note4上Error是OOM,应该显示图片的地方显示黑块

**Comment by Jude95** [comment]
。。。这几个adapter都是对原Adapter的普通封装，这锅我不背啊。你找找OOM具体原因

**Comment by dursss** [comment]
弄好了,可能是图片太大了,现在图片弄小一点就没问题了
