### ISSUE TITLE
cannot resolve JUtils

### ISSUE THREAD

**Issue by Wangct23** [Jude95/RollViewPager#29]
Compile error:
![screen shot 2016-08-24 at 10 07 07](https://cloud.githubusercontent.com/assets/17804057/17916138/10e3b300-69e3-11e6-8f46-243829e47d8a.png)

Version ：
Latest commit 6aaf0b5  23 hours ago @Jude95 Jude95 修改demo数据源为网络获取

**Comment by Jude95** [comment]
不好意思，忘了删，已删。
