### ISSUE TITLE
你好，如何设置占位的图，就是当我网络图片加载失败了，我需要显示一个默认的图，

### ISSUE THREAD

**Issue by tou-zhou** [Jude95/RollViewPager#35]

**Comment by Jude95** [comment]
图片加载与本库无关。

**Comment by zsyh** [comment]
您可以使用glide框架进行网络图片加载。配合RollViewPager1.4.6及以后版本可以实现异步网络图片加载。
glide框架的使用方法可以参考http://www.cnblogs.com/guilin-hu/p/5706916.html

**Comment by Jude95** [comment]
一般项目都有自己一套图片加载，你用的Glide，别人可能用fresco，picasso。某些资源服务有权限的API也需要自行网络加载，即使用Glide一般也要自己进行自定义配置。不可能我直接封装网络加载。
另外我一个才几十k的小库，还自带一个600k的Glide库嘛...

**Comment by zsyh** [comment]
作者您误解我意思了，我那篇回复其实是回issue主的，给他提供了网络图片加载库的一个实例，不是让您把glide框架集成在本库中。
至于为什么提到了1.4.6，是因为这个版本对图片异步加载支持更好了，可以异步修改图片源。
作者您可以在文档中提供图片加载库与本库的结合使用方法的示例。

**Comment by Jude95** [comment]
...好的，不好意思没注意。
