### ISSUE TITLE
能不能实现循环轮播的模式呢？

### ISSUE THREAD

**Issue by pickyourself** [Jude95/RollViewPager#4]

**Comment by Jude95** [comment]
既然都这么想要这个功能，我下个版本就加上吧。

**Comment by Jude95** [comment]
抱歉最近有点忙。拖得久了点。现在好了。看看有没有问题。

**Comment by Lucifer326** [comment]
我想隐藏指示器，有这个函数吗？

**Comment by Jude95** [comment]
1.2.1版本。·setHintView(null);·

**Comment by Lucifer326** [comment]
@Jude95 十分感谢，，可是达到目的，不过mx3 手机上 白屏 不知道为什么。估计是手机的原因....

**Comment by Jude95** [comment]
找到问题了吗，如果不是这个库的问题就close这个issue了吧。
