### ISSUE TITLE
setAdapter()在runOnUiThread中调用时ANR

### ISSUE THREAD

**Issue by zsyh** [Jude95/RollViewPager#41]
我在Activity的onCreate()中调用setAdapter()没有任何问题。但是，出于一种需求，我开启一个线程去获取新的图片，在图片获取结束后在runOnUiThread中调用setAdapter()更换成新的图片时，出现ANR，界面卡死，UI线程CPU满占用，十几秒后才恢复。即使我在getView()中返回new ImageView(container.getContext())，也是一样卡死，说明不是我在getView()中做耗时操作造成的这个ANR。望修复这个bug

==补充：broadcastreceiver的onReceive()事件中进行setAdapter()也不行

**Comment by Jude95** [comment]
是最新的版本吗，我没能复现...你看看最新的demo有问题吗。

**Comment by zsyh** [comment]
最新版本1.4.5，这个问题跟issue#25是同一个问题。稍后提供最小复现代码。

**Comment by zsyh** [comment]
rollPagerView=(RollPagerView)findViewById(R.id.rollviewpager);
        new Thread(new Runnable() {
            @Override
            public void run() {
                
                
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        
                        //ANR happens
                        rollPagerView.setAdapter(new LoopPagerAdapter(rollPagerView) {
                            @Override
                            public View getView(ViewGroup container, int position) {
                                return new ImageView(container.getContext());
                            }

                            @Override
                            public int getRealCount() {
                                return 0;
                            }
                        });
                        
                        
                    }
                });
       
                
            }
        }).start();

**Comment by Jude95** [comment]
了解...我只处理了延迟notifydatasetchange的情景。没处理延迟setAdapter的情景。
自己从来都是立即设置adapter数据加载到了再notifydatasetchange...
我尽量这2天解决。

**Comment by zsyh** [comment]
谢谢，因为有图片更换的需求

**Comment by Jude95** [comment]
1.4.6 试试。

**Comment by zsyh** [comment]
1.4.6版本ANR问题已解决，感谢对issue的关注
