### ISSUE TITLE
如何解决ViewPager和下拉刷新滑动冲突问题

### ISSUE THREAD

**Issue by gmfbilu** [Jude95/RollViewPager#43]
有下拉刷新和viewpager的时候，左右华东bannar很难滑动

**Comment by Jude95** [comment]
那是下拉刷新控件的问题，与本库无关。它把事件拦截了，我有什么办法。
你可以试试`refreshLayout.requestDisallowInterceptTouchEvent(false)`
如果无效，请自己分析你的下拉刷新控件对事件流的控制，进行修改。
