### ISSUE TITLE
1.可不可以增加一个修改viewpage滑动时间的接口；2.如果只有一张图的时候，能不能不autoplay

### ISSUE THREAD

**Issue by Nstd** [Jude95/RollViewPager#45]
如题

**Comment by Jude95** [comment]
你说的是播放间隔时间？`setPlayDelay(int delay)`这个接口？
能不能autoplay是指暂停继续播放？`pause()`与`resume()`这2个接口？

如果你是想在LooperAdapter下，一张图时，不允许左右滑动。这个因为LooperAdapter实现机制的原因办不到。

**Comment by Nstd** [comment]
1. 第一页切换到第二页的动画太快了，这个切换时间的间隔能设置吗？

2. 现在暂时可以用pause()和resume()做，就是用起来比较麻烦了

**Comment by Jude95** [comment]
你是说'setAnimationDurtion(int during)'嘛...
我考虑下LooperAdapter在一张图时的特殊处理吧。

**Comment by Nstd** [comment]
好的，动画那个我周一试试，谢谢~
PS：话说首页README的例子是有，但是没找到API列表，所以有些东西不太好找，能不能完善下文档？

**Comment by Jude95** [comment]
...一般README都只写主要API，也主要起介绍作用。就这样都经常有人不看
库是包含了源码的，API请进源码看左侧API列表。我也都尽量写了javadoc和注释。
你可以看看很多主流库的README及源码的注释文档....

**Comment by Nstd** [comment]
😂 库主说的不无道理，虽然就使用角度来讲，文档是越详细越好，但理想和现实也会有一定的差距，这意味着贡献者会有更多的付出，如果付出没有被尊重（写了也没人看），常常会打击人心，便不再细写了，这也算是个恶性循环。
😄不过还是感谢库主的开源精神~
