### ISSUE TITLE
用LoopPagerAdapter时，getCount值是Integer.MAX_VALUE

### ISSUE THREAD

**Issue by xiaoDongBei90** [Jude95/RollViewPager#48]
用LoopPagerAdapter时，getCount值是Integer.MAX_VALUE，这样会很耗性能的呀

**Comment by Jude95** [comment]
不会，所有页面均做缓存以模拟多页效果。不会存在重复创建页面。
如果你担心，可以自己查查页面创建数量，及CPU内存消耗。
