### ISSUE TITLE
getItemPosition返回值疑问

### ISSUE THREAD

**Issue by summer-zhoujie** [Jude95/RollViewPager#52]
![default](https://cloud.githubusercontent.com/assets/17558918/23840679/3859e8a8-07e2-11e7-9b21-af9d5edb0ecd.PNG)
如图：
返回POSITION_UNCHANGED不是可以减少调用instantiateItem去创建ChildView；
而返回POSITION_NONE则要求每次notify的时候，（清理缓存）clear viewList，从新调用instantiateItem去创建一系列（默认3个）ChildView，加入到viewList；

请问：使用POSITION_NONE的原因，没有弄清楚真正的用意，很困惑，求解

**Comment by summer-zhoujie** [comment]
http://www.jb51.net/article/107257.htm
找到原因了。。。如果这是真的原因，那么我华丽的侮辱了自己

**Comment by Jude95** [comment]
POSITION_NONE就是为了刷新。
另外不用担心重复创建View。只有`DynamicPagerAdapter `与`LoopPagerAdapter `是返回`POSITION_NONE`。而这2个都是我自己实现了一套View缓存机制。从新调用instantiateItem不等于重新创建ChildView。

**Comment by summer-zhoujie** [comment]
首先感谢您耐心的回答！

![default](https://cloud.githubusercontent.com/assets/17558918/23881636/9ffc9af0-0896-11e7-8f45-2a12d9074836.PNG)
![sss](https://cloud.githubusercontent.com/assets/17558918/23881648/b22802a0-0896-11e7-9409-5cbe0f837e4c.PNG)

还有一个疑问是每notify一下，mViewList都会clear一下，导致在instantiateItem里面从新创建，我想将clear的代码注释掉，这样既刷新了界面，又不用从新创建View，这样的思路正确吗

**Comment by Jude95** [comment]
notify...不就是刷新View=重新创建View吗。在原ViewPager和RecycleView里都是这样。不clean旧view...你咋刷新界面。
你如果只是想修改界面,不应该调用notify，直接修改View就好
