### ISSUE TITLE
与Glide结合使用时比例失真bug

### ISSUE THREAD

**Issue by zsyh** [Jude95/RollViewPager#54]
与Glide图片加载框架结合使用时，加载进来的图片有时会比例失真，有时又是比例正常的。请解决比例失真的bug

代码：
LoopPagerAdapter loopPagerAdapter=new LoopPagerAdapter(rollPagerView) {
            @Override
            public View getView(ViewGroup container, int position) {
                ImageView imageView = new ImageView(container.getContext());

                Glide
                        .with(MainFragment.this)
                        .load(xxxxxxxUrl)
                        .centerCrop()
                        //.placeholder(R.color.windowBackground)
                        //.diskCacheStrategy(DiskCacheStrategy.SOURCE)
                        .crossFade()
                        .into(imageView);

                imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
                imageView.setLayoutParams(new                            ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
                return imageView;
            }

            @Override
            public int getRealCount() {
                return rollPicList==null?1:rollPicList.size();
            }

        };

        rollPagerView.setAdapter(loopPagerAdapter);
        rollPagerView.setPlayDelay(4000);
    }

**Comment by Jude95** [comment]
![image](https://cloud.githubusercontent.com/assets/7901171/24861380/21491db4-1e2b-11e7-8192-075b78c6df54.png)
你让ViewPager去解决图片加载问题？？？

**Comment by zsyh** [comment]
首先感谢repo主的开源精神。其次，我觉得有可能是RollViewPager的高度计算有bug而造成的比例失真。
