### ISSUE TITLE
亲爱的博主您好  请问可以实现在最后一张继续滑动后跳转到别的页面吗

### ISSUE THREAD

**Issue by fancker1992** [Jude95/RollViewPager#58]
我一直在用这个轮播控件  后来需要做引导图  第一时间也是想到了咱这个控件  但是现在有个新需求  就是不需要循环轮播  在最后一页继续滑动后直接跳转到主页  请问可以实现吗  或是自己进行修改

**Comment by Jude95** [comment]
...这功能都与这个库无关了。
直接用ViewPager,监听下手势,什么效果都能做。
