### ISSUE TITLE
TimerTask匿名内部类 内存泄露

### ISSUE THREAD

**Issue by yuhangjiayou** [Jude95/RollViewPager#6]
作者你好，很感谢分享你的项目，我在实际应用中发现，RollPagerView中startPlay()用到timer.schedule(new TimerTask() {}这里有个匿名TimerTask内部类会导致内存泄露
![e3036440-e263-48ac-803d-7c5b0ac2fbb5](https://cloud.githubusercontent.com/assets/13059924/12370138/32eecb7e-bc41-11e5-8eaa-ccee888eb9c3.png)
希望作者可以修改一下，小小建议，再次感谢

**Comment by Jude95** [comment]
感谢指出。1.2.2看看还有没有问题。确实匿名内部类异步使用要注意一下内存泄露问题~

**Comment by yuhangjiayou** [comment]
@Jude95 哈，作者，刚用了下你的LoopPagerAdapter，然后发现里面的instantiateItem(ViewGroup container, int position) 方法里面第一句int realPosition = position%getRealCount();这里的getRealCount()会因为get到0而报错,java.lang.ArithmeticException: divide by zero

**Comment by Jude95** [comment]
...真是细心，更新1.2.3看看。
