### ISSUE TITLE
您好，由于recyclerView的回收机制，再次回到rollpagerView的时候又是从第一页开始轮播

### ISSUE THREAD

**Issue by git-cncoder** [Jude95/RollViewPager#60]
请问可以保存轮播的位置吗？ 提供一个方法，可以设置轮播的位置在哪里， 跟ViewPager一样，setCurrentItem()   期待你的回复。Thanks.

**Comment by Jude95** [comment]
getViewPager() ...
不是"和ViewPager一样"。那就是个ViewPager...
注意下使用Looper的话。setCurrentItem的position.请用getCurrentItem获取的值做加减。不要填1.2.3...

**Comment by git-cncoder** [comment]
好的，明天早上使用一下，谢谢你的回复。

**Comment by git-cncoder** [comment]
谢谢。已解决。。
