### ISSUE TITLE
如何使用自己的imageview来加载呢，大哥！

### ISSUE THREAD

**Issue by wongyue** [Jude95/RollViewPager#61]

**Comment by kfgtrehj** [comment]
它只是一个容器，自定义的View是一样能够加载的。你可以描述一下具体的问题。

**Comment by Jude95** [comment]
Meaningless issue

**Comment by wongyue** [comment]
就是我这边有一个自己的ImageVIew，可以加载网络图片和本地的等等，还没找到怎么替换进去，我试了一下直接把你那儿的那个imageView强转成我这个类型的，炸了
