### ISSUE TITLE
如何加载网络图片

### ISSUE THREAD

**Issue by hellobenji** [Jude95/RollViewPager#62]
view.setImageResource(imgs[position]);//这个地方是int类型的 获取的是string的图片地址 该如何用呢
我看还有一个 
        view.setImageURI();这个方法 但是不知道怎么 还请指点一下

**Comment by Jude95** [comment]
...请去看android教学视频从基础学起

**Comment by hellobenji** [comment]
额 好吧 我再研究下 一点印象没有了 。。。。还是谢谢了

**Comment by hellobenji** [comment]
还有啊 我不建议关闭啊。可能很多像我这样的。建议打开也算是方便其他人吧既然已经开源了

**Comment by hellobenji** [comment]
哈哈哈哈哈哈 当时思路理解错了。说明你封装的还不太好哟 我是说对于很基础的同学来说
@Override
    public View getView(ViewGroup container, int position) {

        ImageView view = new ImageView(container.getContext());
        Logger.e("homeShowList.get(position)");
        Glide.with(MyApplication.getInstance())
                .load(homeShowList.get(position))//这个homeShowlist里边装的都是图片的url
                .into(view);

        //view.setImageResource(imgs[position]);
        view.setScaleType(ImageView.ScaleType.CENTER_CROP);
        view.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        return view;
    }

**Comment by Jude95** [comment]
菜谱免费公开，菜免费给你吃，用餐说明也写了。你问如何用筷子夹菜，说明你菜做的不太好哟，对于不太会用筷子的同学来说。

**Comment by hellobenji** [comment]
首先肯定你的开源，我觉得能开源的都很伟大。是一种很高尚的行为。
可能你已经过了那个什么都不懂的阶段。也忘记了那种感觉。
假如真的不会用筷子。很可能就吃不到你那个免费的菜。但是假如你再赠送一份筷子使用教程。如果我是那个不会用筷子的人。我会更感激你。当然你让我去别的地方学会来用筷子再来吃。我依然会感激你。
但是这次也谢谢你的拒绝回答。让我又打开了领一种思路。如果你直接给我筷子。估计我早晚还是去经历找筷子的过程，编程之路，有些经历是不能走捷径的。再次感谢

**Comment by Jude95** [comment]
抱歉，最近这类问题越来越多，有些失去耐心了。
4年前android哪有几个库，github都没几个中文项目。资料教程书都少。谁能给筷子，哪有菜,自己摸黑爬过来，感觉忘不了，还记得一开始一个字一个字敲不用代码提示抄完别人demo学习，还记笔记。
现在学东西都到了张嘴别人喂的地步，轮子一大堆，都到了挑的地步，做开发组装下轮子就好。只是吐槽下最近感觉到的android氛围。
独自探索学习知识的过程解决问题的能力比知识本身更重要。从源码挖掘，翻官方文档，stackoverflow找前人经验等。这样的人才能从后方安逸区突进到前线无人区。
另外...issue不是贴吧。交流请邮件。
