### ISSUE TITLE
请问一下，支持懒加载吗。一次只加载一页的数据

### ISSUE THREAD

**Issue by git-cncoder** [Jude95/RollViewPager#63]
目前我是用 fragment  实现的懒加载。

**Comment by Jude95** [comment]
这只是个ViewPager。关fragment与懒加载什么事了

**Comment by git-cncoder** [comment]
嗯呢， 可能这个只要偏重轮播图放心， 我是viewpager 里面嵌套了 Fragment，没事这个fragment可以自行处理。 这个问题问错了= =，抱歉
