### ISSUE TITLE
只有两张图片时，初始化有问题。

### ISSUE THREAD

**Issue by jaycam23** [Jude95/RollViewPager#7]
如果只有两张图片的话，初始化默认会显示第二张图片，但指示器默认会显示的是第一个。也就是指示器和图片不匹配。只在初始化的时候有这个问题，轮播开始之后就正常了。

**Comment by Jude95** [comment]
看看新版本还有没有问题。

**Comment by jaycam23** [comment]
两张图片的没有问题了。但是三张图片的就不行了。初始图片是显示的第二张，提示器显示的是第一个。

**Comment by Jude95** [comment]
那是个错误...看看现在版本。
