### ISSUE TITLE
直接gradle引用会提示Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by MIkeeJY** [Jude95/RollViewPager#9]
Error:Execution failed for task ':XXXX:processDebugManifest'.
Manifest merger failed with multiple errors, see logs
在主要的 Moudle 中的 AndroidMenifest.xml 如果已有屬性

< application
    android:theme="@android:style/Theme.XXX>
< /application>
則在引用的 Library Moudle 中的 AndroidMenifest.xml 也設有相同的屬性設置
android:theme="@android:style/Theme.XXX
則會報出上述錯誤，將 Library Moudle 中的該屬性消除即可。

**Comment by Jude95** [comment]
是依赖这个库时有问题吗？
这个库里的Manifest的application并没有android:theme属性。

**Comment by MIkeeJY** [comment]
但是有package name 等 冲突了。。。

**Comment by MIkeeJY** [comment]
application 节点冲突了

**Comment by cayden** [comment]
可以在project.properties文件添加 sdk.buildtools=23.0.3

**Comment by aqianchu** [comment]
compileSdkVersion and buildToolsVersion should be equal to Main Module in Library Module's build.gradle
